name: Weightwatch
options:
  bundleIdPrefix: com.shimondeitel.weightlog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Weightwatch:
    type: application
    platform: iOS
    sources:
      - path: Weightwatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.weightlog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Weightwatch/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  WeightwatchTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: WeightwatchTests
      - path: Weightwatch.storekit
    dependencies:
      - target: Weightwatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.weightlog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  WeightwatchUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: WeightwatchUITests
    dependencies:
      - target: Weightwatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.weightlog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Weightwatch:
    build:
      targets:
        Weightwatch: all
        WeightwatchTests: [test]
        WeightwatchUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Weightwatch.storekit
    test:
      config: Debug
      storeKitConfiguration: Weightwatch.storekit
      targets:
        - WeightwatchTests
        - WeightwatchUITests
    archive:
      config: Release
